name: Deploy using FTP

on:
  push:
    branches: [ main ]   # change if needed

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # No build steps needed for PHP core — just upload the files
      - name: Deploy repo to cPanel via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.CPANEL_FTP_HOST }}
          username: ${{ secrets.CPANEL_FTP_USER }}
          password: ${{ secrets.CPANEL_FTP_PASS }}
          protocol: ftps                       # use 'ftp' if your host doesn't support FTPS
          local-dir: ./                        # upload everything from repo root
          server-dir: /public_html/            # <-- set this to your target dir
          exclude: |
            **/.git*
            **/.github/**
            **/.DS_Store
            **/node_modules/**
            **/vendor/**.map
